import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Header from '../components/header'
import Hero from '../components/hero'
import About from '../components/about'
import WorkExperience from '../components/workExperience'
import Skills from '../components/skills'
import Projects from '../components/projects'
import Contact from '../components/contact'
import { Experience, PageInfo, Project, Skill, Social } from '../typings'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchExperiences } from '../utils/fetchExperience'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchProjects } from '../utils/fetchProjects'
import { fetchSocials } from '../utils/fetchSocials'

type Props = {
    pageInfo: PageInfo
    experiences: Experience
    projects: Project
    skills: Skill
    socials: Social
}

const Home = ({pageInfo, experiences, projects, skills, socials}: Props) => {
  return (
    <div className={'bg-slate-900 text-white h-screen snap-y snap-mandatory overflow-scroll z-0 overflow-y-scroll overflow-x-hidden scrollColor'}>
      <Head>
        <title>Sebastian Manion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />

      {/* hero */}
      <section  id='hero' className='snap-start'>
        <Hero />
      </section>

      {/* about */}
      <section id='about' className='snap-center'>
        <About />
      </section>

      {/* experience */}
      <section id='experience' className='snap-center'>
        <WorkExperience />
      </section>

      {/* skills */}
      <section id='skills' className='snap-center'>
        <Skills />
      </section>

      {/* projects */}

      <section id='projects' className='snap-center'>
        <Projects />
      </section>

      {/* contact me */}

      <section id='contact' className='snap-center'>
        <Contact />
      </section>

        <footer className='sticky bottom-5 flex justify-center w-full'>
              <Link href="#hero">
                <div className='flex w-fit items-center just ify-center'>
                  <Image src={'https://i.imgur.com/DkIiGlB.png'} alt='home' height={45} width={45} className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer' />
                </div>
              </Link>
        </footer>      
    </div>
  )
}

export default Home

const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo()
  const experiences: Experience[] = await fetchExperiences()
  const skills: Skill[] = await fetchSkills()
  const projects: Project[] = await fetchProjects()
  const socials: Social[] = await fetchSocials()

  return {
    props: {
      pageInfo,
      experiences,
      skills,
      projects,
      socials,
    },

    revalidate: 300
  }
}
