import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../components/header'
import Hero from '../components/hero'
import About from '../components/about'
import WorkExperience from '../components/workExperience'
import Skills from '../components/skills'
import Projects from '../components/projects'
import Contact from '../components/contact'

const Home: NextPage = () => {
  return (
    <div className={'bg-slate-900 text-white h-screen snap-y snap-mandatory overflow-scroll z-0 overflow-y-scroll overflow-x-hidden scrollColor'}>
      <Head>
        <title>Sebastian Manion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />

      {/* hero */}
      <section  id='hero' className='snap-start'>
        <Hero />
      </section>

      {/* about */}
      <section id='about' className='snap-center'>
        <About />
      </section>

      {/* experience */}
      <section id='experience' className='snap-center'>
        <WorkExperience />
      </section>

      {/* skills */}
      <section id='skills' className='snap-center'>
        <Skills />
      </section>

      {/* projects */}

      <section id='projects' className='snap-center'>
        <Projects />
      </section>

      {/* contact me */}

      <section id='contact' className='snap-center'>
        <Contact />
      </section>
      
    </div>
  )
}

export default Home
